- charts/mageai/templates/serviceaccount.yaml
Not use default namespace in service account.
tested locally
cc:
> [xy] Not use default namespace in service account.

- .github/actions/chart-testing/Dockerfile
- .github/actions/chart-testing/action.yml
- .github/actions/chart-testing/entrypoint.sh
- .github/actions/kubeconform/Dockerfile
- .github/actions/kubeconform/action.yml
- .github/actions/kubeconform/entrypoint.sh
- .github/workflows/development.yml
Runs `helm/chart-testing` and `yannh/kubeconform` against the chart on any pull request.
Dispatched the workflow on an PR against my forked repo.
> Some basic chart testing for the Github Action Workflow

- charts/mageai/Chart.yaml
Sorts Chart.yaml attributes alphabetical and adds missing attributes
- Chart Testing
> Sort and add missing Chart.yaml attributes

- charts/mageai/Chart.yaml
Adds Artifact Hub related annotations.
- Chart Testing
> Add some Artifact Hub annotations

- .github/actions/chart-testing/entrypoint.sh
added helm dependency command in entrypoint
> added dependency redis chart for CI test

- .gitignore
- examples/README.md
- examples/aks/azure-files-pvc.yaml
Create examples folder, and add AKS pvc yaml file.
tested on AKS
> [dy] Add examples

- charts/mageai/Chart.yaml
Bump chart version to 0.1.5
Update Mage version to 0.9.44
tested deploy to local k8s cluster with the helm chart
cc:
> [xy] Bump chart version to 0.1.5

- .github/workflows/release.yml
Install helm dependency in chart release action.
Fix error: https://github.com/mage-ai/helm-charts/actions/runs/6855099515/job/18639446867
test in github action
cc:
> [xy] Install helm dependency in chart release action.

- .github/workflows/release.yml
Allow manually trigger release workflow so that we can test the release action on a separate branch without merging it.
Also use the azure/setup-helm@v3 to install the helm
to be tested after merging this change.
cc:
> [xy] Allow manually trigger release workflow.

- charts/mageai/Chart.yaml
Close: https://github.com/mage-ai/helm-charts/issues/32
* Chart Testing
cc:
> [xy] Update the mageai version in artifact hub config.

- charts/mageai/templates/serviceaccount.yaml
This is needed for stopping and resuming workspace instances
Similar to previous PR https://github.com/mage-ai/helm-charts/pull/27
cc: @dy46 , @adelcast
> Update serviceaccount.yaml w statefulsets/scale resource

- charts/mageai/templates/serviceaccount.yaml
The workspace manager service account needs pods/exec permissions to get activity data from the workspaces.
cc:
> [dy] Add pods/exec permission

- charts/mageai/Chart.yaml
Bump version to 0.2.2
tested the recent helm chart changes locally
cc:
> [xy] Bump version to 0.2.2

- charts/mageai/Chart.yaml
Bump version to 0.2.3
* https://github.com/mage-ai/helm-charts/pull/45
Tested locally
cc:
> [xy] Bump version to 0.2.3

- charts/mageai/Chart.yaml
Bump version to 0.2.4
* https://github.com/mage-ai/helm-charts/pull/52
tested locally
cc:
> [xy] Bump version to 0.2.4

- charts/mageai/Chart.yaml
- charts/mageai/templates/pv.yaml
- charts/mageai/values.yaml
Provision PVC in helm chart
tested in EKS with EFS PVC
cc:
> [xy] Provision PVC in helm chart

- charts/mageai/Chart.lock
- charts/mageai/Chart.yaml
Update PostgreSQL and Redis
- Local instances are running
cc:
> update chart to us the last version of the deps

- charts/mageai/Chart.yaml
- charts/mageai/templates/cleanup-cronjob.yaml
- charts/mageai/values.yaml
Add cleanup job to helm chart to clean variables and logs
tested locally with value
```
cleanupJob:
enabled: true
```
cc: @tommydangerous @johnson-mage
> [xy] Add cleanup job to helm chart and bump version to 0.2.7

- charts/mageai/Chart.yaml
Update helm chart to version 11 and update mage image version to 0.9.76
+ include previous changes
cc:
> Update helm chart to version 11 and update mage image version to 0.9.76

- charts/mageai/Chart.yaml
- charts/mageai/templates/deployment.yaml
- charts/mageai/templates/scheduler.yaml
- charts/mageai/templates/webservice.yaml
- charts/mageai/values.yaml
Support configuring init container image urls.
Bump version to 0.2.12
tested helm chart locally
cc:
> [xy] Support configuring init container image urls
