- charts/mageai/templates/service.yaml
- charts/mageai/values.yaml
Hope you appriciate a direct pull request. 
This PR adds support for adding custom service annotations.
I have deployed the helm chart successfully on Azure, resulting in the service getting a private IP address.  
For the test I have used to following terraform code:
```tf
resource "helm_release" "mage" {
name      = "mage"
chart     = "/path/to/my/customized/charts/mageai"
namespace = "mage"
set {
name  = "service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"
value = "true"
type  = "string"
}
set {
name  = "service.type"
value = "LoadBalancer"
}
}
```
> Add support for service annotations

- charts/mageai/Chart.yaml
- charts/mageai/values.yaml
Using a fixed tag is recommended to avoid accidental upgrades.
As the `appVersion` is defined, we don't need to add a tag in values. I have removed the tag value.
In order to not accidentally downgrade some installations, I have updated the `appVersion` to the current latest `0.9.11`.
- kubeconform
- helm template -> Produces the correct tag `0.9.11
> Remove latest tag, to prevent accidental upgrades

- charts/mageai/templates/deployment.yaml
- charts/mageai/values.yaml
Based on [feature request](https://mageai.slack.com/archives/C03KW780J2F/p1691344029730949)
Currently the only possible volumeMount mountPath has been `/home/src`. In order to
- change the mount path
- add more volumes
I have changed the volume value to `extraVolumes` and `extraVolumeMounts` specification. The default values will still produce the same volume and mount as before.
The old `volumes` config is still supported, if `extraVolumes` is not configured.
- kubeconform
- helm template -> correct mounts
> More customisation options for Volumes

- charts/mageai/values.yaml
This is me being nit-picky...
Based on [kube-score](https://github.com/zegl/kube-score): NodePort services should be avoided as they are insecure, and can not be used together with NetworkPolicies. LoadBalancers or use of an Ingress is recommended over NodePorts.
I believe any helm chart default values should be based on best practice.
Changed the default value for service.type to `LoadBalancer`
- kubeconform
- kube-score
- tested on Docker Desktop Kubernetes
> Change Values service.type to LoadBalancer

- charts/mageai/values.yaml
Forgot to put the type hint `""` to `image.tag` after removing `latest`
- kubeconform
- helm template -> manual check whether it still shows the `appVersion` as `image.tag` if not configured in values
> Add type hint for image.tag

- charts/mageai/templates/serviceaccount.yaml
Changed the name of the role and role binding to use `{{ include "mageai.fullname" . }}` as prefix.
This is more in line with the naming of the rest of the resources, which are all prefixed with or named by `{{ include "mageai.fullname" . }}`
- kubeconform
- helm template -> manual check
- deployed on Docker Desktop Kubernetes
> Prefix job-manager with fullname

- charts/mageai/templates/_helpers.tpl
- charts/mageai/templates/configmap.yaml
- charts/mageai/templates/deployment.yaml
- charts/mageai/templates/secrets.yaml
- charts/mageai/values.yaml
Mage has quite a lof of possible environment variables. To organise them, I like to put them into a configmap. This configmap is then used as environment variables.
Same goes for secrets. I also added a hint, to use a secret manager if possible.
Old env config is still possible -> minor change
- kubeconform
- helm template -> manual check
- deployed on Docker Desktop Kubernetes and checked whether the env variables are actually sourced
> Add configmap and secrets as env variables

- charts/mageai/templates/serviceaccount.yaml
Resolves #6 
Adds workspace manager role, based on [documented](https://docs.mage.ai/developing-in-the-cloud/workspaces/kubernetes) role definition.
- kubeconform
- helm template -> manual check
- deployed on Docker Desktop Kubernetes -> service, pvc, statefulset, pod are created
> Add workspace manager role

- charts/mageai/Chart.yaml
Bump App Version to current latest: 0.9.16
Deployed to Docker Desktop Kubernetes
> Bump App Version to 0.9.16

- .gitattributes
- .gitignore
Im working on Windows, therefore normalizing `*.sh` to `LF` in the working directory is needed in order to correctly build docker images.
Also when creating a helm package locally, we need to prevent the package from being commited.
Manual check, whether .gitattributes and .gitignore take affect
> Add .gitattributes & .gitignore

- charts/mageai/templates/deployment.yaml
- charts/mageai/values.yaml
Adds possibility to configure `readinessProbe` and `livenessProbe`.
Also removes `livenessProbe` if not configured. Rather have no `livenessProbe` than a poorly configured one. A poorly configured `livenessProbe` will trigger a premature restart of the container. The default parameters by kubernetes are:
> - `initialDelaySeconds`: Number of seconds after the container has started before startup, liveness or readiness probes are initiated. If a startup probe is defined, liveness and readiness probe delays do not begin until the startup probe has succeeded. Defaults to 0 seconds. Minimum value is 0.
> - `periodSeconds`: How often (in seconds) to perform the probe. Default to 10 seconds. The minimum value is 1.
> - `timeoutSeconds`: Number of seconds after which the probe times out. Defaults …
> Prevent premature restarts

- charts/mageai/Chart.yaml
- charts/mageai/templates/deployment.yaml
Bump version to 0.1.4 and make configs backward compatible.
The old values.yml uses `env` and `volumes`. The new values.yml uses `extraEnvs` and `extraVolumes`.
Tested install helm chart with old values.yaml and new values.yml
cc:
> [xy] Bump version to 0.1.4 and make configs backward compatible.

- charts/mageai/templates/serviceaccount.yaml
Workspace manager has an option to add routes to existing ingresses, which requires explicit permissions.
Use modified helm chart to deploy on K8 cluster on AWS. Verified additional routes can be added to an existing ingress.
> serviceaccount: enable ingress control

- charts/mageai/templates/_helpers.tpl
- charts/mageai/templates/tests/test-connection.yaml
Helm test is currently failing when MAGE_BASE_PATH is used. Fix helm charts to include it in the route, if defined
Manually tested with/without MAGE_BASE_PATH defined
> add support for non empty MAGE_BASE_PATH

- charts/mageai/Chart.lock
- charts/mageai/Chart.yaml
- charts/mageai/requirements.yaml
- charts/mageai/templates/_helpers.tpl
- charts/mageai/templates/deployment.yaml
- charts/mageai/templates/scheduler.yaml
- charts/mageai/templates/webservice.yaml
- charts/mageai/values.yaml
Added Redis dependency to the chart to support multiple replicas
Standalone scheduler and webserver option added to the chart
Deployed standalone mode with Redis enabled in the chart as well as external Redis URL - passed
Deployed multiple replicas with Redis enabled in the chart as well as external Redis URL - passed
@wangxiaoyou1993, @dy46, @johnson-mage, @tommydangerous
> Redis support

- charts/mageai/templates/scheduler.yaml
- charts/mageai/templates/webservice.yaml
- charts/mageai/values.yaml
* Set default value of standaloneScheduler to false. (not break current default behaviour)
* Add instance type env var to scheduler and web server. Will update the Mage server code to get the instance type from env var if it exists
cc:
> [xy] Updates on standalone scheduler configs

- charts/mageai/Chart.yaml
- charts/mageai/templates/deployment.yaml
Fix the thing I didn't do right yesterday - indent extraContainers 8 instead of 12.
Verified that the yaml put the container at the right level.
cc:
@tommydangerous
> fix(containers): extraContainers need to be indented 8, not 12

- charts/ingress/.helmignore
- charts/ingress/Chart.yaml
- charts/ingress/templates/NOTES.txt
- charts/ingress/templates/_helpers.tpl
- charts/ingress/templates/ingress.yaml
- charts/ingress/values.yaml
- charts/mageai/values.yaml
Create separate helm chart to create ingress for Mage. Including the ingress with the main helm chart can lead to issues when upgrading the chart. I also added a comment to the main helm chart to recommend creating the ingress separately.
Tested locally
> [dy] Add ingress chart

- charts/mageai/templates/configmap.yaml
- charts/mageai/templates/secrets.yaml
- Fix configmap and secret template
**configmap**
Run test template with `helm template -s templates/configmap.yaml --debug`
input:
```yaml
config:
test: "test"
test2: "test2"
```
output:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: mageai-env
labels:
helm.sh/chart: mageai-0.2.0
app.kubernetes.io/name: mageai
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "0.9.55"
app.kubernetes.io/managed-by: Helm
data:
test: test
test2: test2
```
**secret**
Run test template with `helm template -s templates/secrets.yaml --debug`
input:
```yaml
secret:
secret: "1"
secret2: "2"
```
output: 
```yaml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
name: mageai-secret-env
labels:
helm.sh/chart: mageai-0.2.0
app.kubernetes.io/name: mageai
app.kubernetes.io/instance: …
```
> fix: fix configmap and secret

- charts/mageai/templates/deployment.yaml
Allows setting `.Values.image.digest` in order to uniquely specify a particular image to deploy
```helm lint```
and
```helm template -f values.yml ./charts/mageai > out.yml```
with the following `values.yml` file, trying all combinations of tag and digest enabled/disabled. I manually checked the output to confirm it looked as intended.
```
replicaCount: 1
image:
repository: mageai/mageai
pullPolicy: Always
#tag: "0.9.56" # At least two images exist with this tag
digest: "sha256:41be240147ca04d0954bb9544ac0675e86de78995cf739c2635ec398b43741cc"
```
Example output snippet:
```
securityContext:
{}
image: "mageai/mageai@sha256:41be240147ca04d0954bb9544ac0675e86de78995cf739c2635ec398b43741cc"
imagePullPolicy: Always
ports:
- name: http
```
> Allow specifying an image digest to deploy

- charts/mageai/templates/scheduler.yaml
- charts/mageai/templates/webservice.yaml
- charts/mageai/values.yaml
Adding the resource configuration in values file let you deploy scheduler and webserver with different cpu and memory configurations
Deployed in local k8s cluster and verified that the custom resource configurations are working or not
> Scheduler and Webserver with separate resource configuration

- charts/mageai/templates/hpa.yaml
- charts/mageai/values.yaml
Support horizontal pod scaler in deployment.
Example config in values.yaml
```
hpa:
minReplicas: 1
maxReplicas: 10
targetCPUUtilizationPercentage: 50
```
tested locally
cc:
> [xy] Support horizontal pod scaler in deployment

- charts/mageai/templates/deployment.yaml
When updating the port of the load balancer the container port also gets updated but it is not possible to have mageai run on a different port than 6789.
Deployed the helm chart and tested the connection from the Load Balancer
cc:
> service is always running on 6789 (cannot be changed)

- charts/mageai/Chart.lock
- charts/mageai/Chart.yaml
- charts/mageai/templates/deployment.yaml
- charts/mageai/templates/scheduler.yaml
- charts/mageai/templates/webservice.yaml
- charts/mageai/values.yaml
Add postgres as optional dependency and bump version to 0.2.5
Tested the following case
* set standalone scheduler to false
* set standalone scheduler to true
* set postgresql auth
notes: when reinstalling the helm chart, remember to manually delete the PVC created by the postgres service to get it cleaned up.
cc:
> [xy] Add postgres as optional dependency and bump version to 0.2.5

- charts/mageai/Chart.lock
- charts/mageai/Chart.yaml
Reverts mage-ai/helm-charts#64
Revet since upgrading the postgres is a breaking change
> Revert "update chart to us the last version of the deps"

- charts/mageai/Chart.yaml
- charts/mageai/templates/cleanup-cronjob.yaml
- charts/mageai/values.yaml
Add optional cli args to cleanup jobs and bump version to 0.2.9
tested on pro cluster with config
cc: @tommydangerous @johnson-mage
> [xy] Add optional cli args to cleanup jobs and bump version to 0.2.9

- charts/mageai/Chart.yaml
- charts/mageai/templates/cleanup-cronjob.yaml
- charts/mageai/values.yaml
Give control to the user to define the best schedule to clean up the variables and the logs.
The default value will be once per hour, it was the default value before this PR.
Bump version to `0.2.10`
cc: @tommydangerous 
First I installed the `minikube` to have a local env to test the helm install.
I changed the values.yaml to have schedule define:
```yaml
cleanupJob:
enabled: true
clean_variable_cli_args: ""
clean_log_cli_args: ""
schedule_cron: "* * * * *"
```
Test the default from the template. To achieve this I used the schedule define as:
```yaml
cleanupJob:
enabled: true
clean_variable_cli_args: ""
clean_log_cli_args: ""
```
> Allow users to define the schedule for the cleanup job

- charts/mageai/templates/deployment.yaml
- charts/mageai/templates/scheduler.yaml
- charts/mageai/templates/webservice.yaml
- charts/mageai/values.yaml
It will give the possibility to have additional pod labels.
I tested the helm chart locally and it worked like a charm.
cc:
https://github.com/mage-ai/helm-charts/issues/72
> posibility to have additional pod labels.

- charts/mageai/values.yaml
Close: https://github.com/mage-ai/helm-charts/issues/81
This pull request updates the Helm chart configuration for MageAI to specify custom container images for both PostgreSQL and Redis. These changes improve control over the deployment by allowing explicit selection of image versions and registries.
**PostgreSQL image configuration:**
* Added the `image` section to `postgresql` with registry, repository, tag, and pull policy, specifying the use of `bitnamilegacy/postgresql:16.3.0-debian-12-r19` from Docker Hub.
**Redis image configuration:**
* Added the `image` section to `redis` with registry, repository, tag, and pull policy, specifying the use of `bitnamilegacy/redis:7.2.1-debian-11-r0` from Docker Hub.
tested locally
cc:
> [xy] Use bitnamilegacy repository for postgresql and redis image.
